baseURL = "https://shkku.github.io"
languageCode = "en-US"
title = "patternMatchingPatterns"
theme = 'nostyleplease'
enableRobotsTXT = true


disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[params]
  description = "Personal notes on code, ideas, and experiments."
  title = "Lumen's Blog"

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
