baseURL = "https://shkku.github.io/"
languageCode = "en-US"
title = "mumbling in the void"
theme = "nostyleplease"
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[params]
  description = "\"どこにいたって、人はつながっているのよ。\""
  favicon = "favicon.ico"

  [params.theme_config]
    appearance = "auto"
    back_home_text = ".."
    date_format = "2006-01-02"
    isListGroupByDate = true
    isShowFooter = true
    show_description = true

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
